### ISSUE TITLE
Revisit Event and LessonEvent CRUD

### ISSUE THREAD

**Issue by auroranavas** [ISPP-G5/NexONG_Backend#57]
Implement the restrictions. The maxCapacity should be higher or equal than the attendees etc.

**Comment by JuanluRM** [comment]
Aditional changes needs to be made: in the model, has been reported that in the Event and Lesson classes, the atribute Educators has to be optional and Attendees in Meeting has to be optional as well. Aditionally the atribute postal code on the class Volunteer has to change because there are cases where the the postal code starts with 0 and has 4 numbers and the actual validators don't allow that. It's recomended to change it into a String attribute and using "regex" as validator so it doesn't conflict with the .json that stores the dummy data prepared beforehand.
